# Generated by Django 2.2.1 on 2019-06-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('price_range', models.CharField(choices=[('LT10', 'LessThen10'), ('GE10', 'GreaterEqual10'), ('GE20', 'GreaterEqual20')], max_length=4)),
                ('cuisine', models.CharField(choices=[('KOR', 'KoreaCuisine'), ('JAP', 'JapanCuisine'), ('CHI', 'ChinaCuisine'), ('WES', 'WesternCuisine'), ('WOR', 'WorldCuisine'), ('BUF', 'Buffet'), ('CAF', 'Cafe'), ('PUB', 'Pub')], max_length=3)),
            ],
        ),
    ]
